cofocofo/cofocofo

daily_boj/M9/D6/20207_달력_김홍균.cpp

2021/09/06 daily_boj --- 20207 / 달력 --- 김홍균

---

daily_boj/M9/D7/18291_비요뜨의_징검다리_건너기_김홍균.cpp

2021/09/07 daily_boj --- 18291 / 비요뜨의 징검다리 건너기 --- 김홍균

---

daily_boj/M9/D7/18291_비요뜨의징검다리건너기_한승주.py

처음에 그냥 2의 N-2승 때렸다가 안돼서
분할정복 재귀로 구현 후 통과시켰습니다.
N=1일때 예외처리는 함수 내에서 N-2가 음수일떄 1을 반환하도록 해줬습니다.

2021 09 07 daily_boj --- 18291 / 비요뜨의 징검다리 건너기 --- 한승주

---

daily_boj/M9/D8/17951_흩날리는 시험지속에서 내 평점이 느껴진거야_한승주.py

탐색 변수는 그룹합의 최솟값.
비교 변수는 최소 그룹의 갯수 K로 비교해 탐색 진행했습니다.

2021 09 08 daily_boj --- 17951 / 흩날리는 시험지속에서 내 평점이 느껴진거야--- 한승주

---

daily_boj/M9/D8/17951_흩날리는_시험지_속에서_내_평점이_느껴진거야_김홍균.cpp

2021/09/08 daily_boj --- 17951 / 흩날리는 시험지 속에서 내 평점이 느껴진거야 ---  김홍균

---

daily_boj/M9/D9/6568_파이썬을_만든_귀도반로썸_한승주.py

EOF 입력문제 푼게 2번짼데 이번에도 한참걸렸습니다..
다음엔 오래 안걸리길..
비트문제라기엔 연산이 하나도 없었네요

2021 09 09 daily_boj --- 6568 / 귀도 반 로썸은 크리스마스날 심심하다고 파이썬을 만들었다.--- 한승주

---

weekly_codeforces/M9/D26 - Codeforces Round #734 (Div. 3)/A - Polycarp and Coins/A_이유진.java
weekly_codeforces/M9/D26 - Codeforces Round #734 (Div. 3)/B1 - Wonderful Coloring - 1/B1_이유진.java
weekly_codeforces/M9/D26 - Codeforces Round #734 (Div. 3)/B2 - Wonderful Coloring - 2/B2_이유진.java

2021/09/26 Codeforces Round #734 (Div. 3) --- 이유진

---

weekly_codeforces/M10/D2 - Codeforces Round #731 (Div. 3)/A - Shortest Path with Obstacle/A_김홍균.cpp
weekly_codeforces/M10/D2 - Codeforces Round #731 (Div. 3)/B - Alphabetical Strings/B_김홍균.cpp
weekly_codeforces/M10/D2 - Codeforces Round #731 (Div. 3)/C - Pair Programming/C_김홍균.cpp
weekly_codeforces/M10/D2 - Codeforces Round #731 (Div. 3)/D - Co-growing Sequence/D_김홍균.cpp
weekly_codeforces/M10/D2 - Codeforces Round #731 (Div. 3)/E - Air Conditioners/E_김홍균.cpp

2021/10/02 Codeforces Round #731 (Div. 3) --- 김홍균

---

weekly_codeforces/M10/D11 - Codeforces Round #725 (Div. 3)/A - Stone Game/A_우지현.cpp
weekly_codeforces/M10/D11 - Codeforces Round #725 (Div. 3)/B - Friends and Candies/B_우지현.cpp
weekly_codeforces/M10/D11 - Codeforces Round #725 (Div. 3)/C - Number of Pairs/C_우지현.cpp
weekly_codeforces/M10/D11 - Codeforces Round #725 (Div. 3)/D - Another Problem About Dividing Numbers/D_우지현.cpp
weekly_codeforces/M10/D11 - Codeforces Round #725 (Div. 3)/E - Funny Substrings/E_우지현.cpp
weekly_codeforces/M10/D11 - Codeforces Round #725 (Div. 3)/F - Interesting Function/F_우지현.cpp

A, B, C, F 정답, D 시간초과, E 메모리 초과입니다....

2021/10/11 Codeforces Round #725 (Div. 3) --- 우지현

---

weekly_codeforces/M10/D11 - Codeforces Round #725 (Div. 3)/A - Stone Game/A_이민동.java
weekly_codeforces/M10/D11 - Codeforces Round #725 (Div. 3)/B - Friends and Candies/B_이민동.java
weekly_codeforces/M10/D11 - Codeforces Round #725 (Div. 3)/C - Number of Pairs/C_이민동.java
weekly_codeforces/M10/D11 - Codeforces Round #725 (Div. 3)/F - Interesting Function/F_이민동.java

주석을 자세히 달진 못했습니다.. 나머지 문제의 코드도 주중에 올리도록 하겠습니다.

2021/10/12 Codeforces Round #725 (Div. 3) --- 이민동

---

weekly_codeforces/M10/D24 - Codeforces Round #713 (Div. 3)/A - Spy Detected/A_김민수.java
weekly_codeforces/M10/D24 - Codeforces Round #713 (Div. 3)/B - Almost Rectangle/B_김민수.java
weekly_codeforces/M10/D24 - Codeforces Round #713 (Div. 3)/C - A-B Palindrome/C_김민수.java

2021/10/24 Codeforces Round #713 (Div. 3) --- 김민수

---

weekly_codeforces/M10/D24 - Codeforces Round #713 (Div. 3)/A - Spy Detected/A_이민동.cpp
weekly_codeforces/M10/D24 - Codeforces Round #713 (Div. 3)/B - Almost Rectangle/B_이민동.cpp
weekly_codeforces/M10/D24 - Codeforces Round #713 (Div. 3)/D - Corrupted Array/D_이민동.cpp

2021/10/24 Codeforces Round #713 (Div.3) --- 이민동

---

weekly_codeforces/M10/D30 - Codeforces Round #710 (Div. 3)/A - Strange Table/A_김주환.java
weekly_codeforces/M10/D30 - Codeforces Round #710 (Div. 3)/C - Double-ended Strings/C_김주환.java

2021/10/30 Codeforces Round #710 (Div. 3) --- 김주환

2021/10/30 Codeforces Round #710 (Div. 3) --- 김주환

---

weekly_codeforces/M10/D30 - Codeforces Round #710 (Div. 3)/A - Strange Table/A.java
weekly_codeforces/M10/D30 - Codeforces Round #710 (Div. 3)/B - Partial Replacement/B.java
weekly_codeforces/M10/D30 - Codeforces Round #710 (Div. 3)/C - Double-ended Strings/C.java

2021/10/30 Codeforces Round #710 (Div. 3) --- 이유진

---

weekly_codeforces/M10/D11 - Codeforces Round #725 (Div. 3)/G - Gift Set/F_한승주.py
weekly_codeforces/M10/D30 - Codeforces Round #710 (Div. 3)/A - Strange Table/A_한승주.py
weekly_codeforces/M10/D30 - Codeforces Round #710 (Div. 3)/B - Partial Replacement/B_한승주.py
weekly_codeforces/M10/D30 - Codeforces Round #710 (Div. 3)/C - Double-ended Strings/C_한승주.py
weekly_codeforces/M10/D30 - Codeforces Round #710 (Div. 3)/D - Epic Transformation/D_한승주.py
weekly_codeforces/M9/D19 - Codeforces Round #739 (Div. 3)/A - Dislike of Threes/A_한승주.py
weekly_codeforces/M9/D19 - Codeforces Round #739 (Div. 3)/B - Who's Opposite/B_한승주.py
weekly_codeforces/M9/D19 - Codeforces Round #739 (Div. 3)/C - Infinity Table/C_한승주.py
weekly_codeforces/M9/D19 - Codeforces Round #739 (Div. 3)/D - Make a Power of Two/D_한승주.py
weekly_codeforces/M9/D19 - Codeforces Round #739 (Div. 3)/E - Polycarp and String Transformation/E_한승주.py
weekly_codeforces/M9/D26 - Codeforces Round #734 (Div. 3)/A - Polycarp and Coins/A_한승주.py
weekly_codeforces/M9/D26 - Codeforces Round #734 (Div. 3)/B1 - Wonderful Coloring - 1/B1_한승주.py
weekly_codeforces/M9/D26 - Codeforces Round #734 (Div. 3)/B2 - Wonderful Coloring - 2/B2_한승주.py
weekly_codeforces/M9/D26 - Codeforces Round #734 (Div. 3)/C - Interesting Story/C_한승주.py
weekly_codeforces/M9/D26 - Codeforces Round #734 (Div. 3)/D1 - Domino (easy version)/D1_한승주.py
weekly_codeforces/M9/D28 - Codeforces Round #744 (Div. 3)/A - Casimir's String Solitaire/A_한승주.py
weekly_codeforces/M9/D28 - Codeforces Round #744 (Div. 3)/B - Shifting Sort/B_한승주.py
weekly_codeforces/M9/D28 - Codeforces Round #744 (Div. 3)/C - Ticks/C_한승주.py
weekly_codeforces/M9/D28 - Codeforces Round #744 (Div. 3)/D - Productive Meeting/D_한승주.py

당일 외출이 있어서 재풀이는 못했씁니다.
외출 다녀와서 내일까지 해놓겠스니다.

2021/10/30 Codeforces Round #710 (Div. 3) --- 한승주

---

weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/A - Dense Array/A_우지현.cpp
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/B - Balanced Remainders/B_우지현.cpp
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/C - Sum of Cubes/C_우지현.cpp
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/D - Permutation Transformation/D_우지현.cpp

2021/11/06 Codeforces Round #702 (Div. 3) --- 우지현

---

weekly_codeforces/M11/D02 - Codeforces Round #753 (Div. 3)/A - Linear Keyboard/A_김민수.java
weekly_codeforces/M11/D02 - Codeforces Round #753 (Div. 3)/B - Odd Grasshopper/B_김민수.java
weekly_codeforces/M11/D02 - Codeforces Round #753 (Div. 3)/C - Minimum Extraction/C_김민수.java

2021/11/02 Codeforces Round #753 (Div. 3) --- 김민수

---

weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/A - Dense Array/A_한승주.py
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/B - Balanced Remainders/B_한승주.py
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/C - Sum of Cubes/C_한승주.py
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/D - Permutation Transformation/D_한승주.py
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/E - Accidental Victory/E_한승주.py
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/F - Equalize the Array/F_한승주.py
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/G - Old Floppy Drive/G_한승주.py

G번 cycle수 구하는 공식 education참고했는데 이해가 잘 안갑니다..
이해가신분 리뷰 부탁드려요..

2021/11/06 Codeforces Round #702 (Div. 3) --- 한승주

---

weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/A - Dense Array/A_김민수.java
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/B - Balanced Remainders/B_김민수.java
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/C - Sum of Cubes/C_김민수.java
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/D - Permutation Transformation/D_김민수.java

2021/11/06 Codeforces Round #702 (Div. 3) --- 김민수

---

weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/A - Dense Array/A_이유진.java
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/B - Balanced Remainders/B_이유진.java
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/C - Sum of Cubes/C_이유진.java
weekly_codeforces/M11/D06 - Codeforces Round #702 (Div. 3)/D - Permutation Transformation/D_이유진.java

2021/11/06 Codeforces Round #702 (Div. 3) --- 이유진

---

weekly_codeforces/M11/D13 - Codeforces Round #697 (Div. 3)/A - Odd Divisor/A_김민수.java
weekly_codeforces/M11/D13 - Codeforces Round #697 (Div. 3)/B - New Year's Number/B_김민수.java
weekly_codeforces/M11/D13 - Codeforces Round #697 (Div. 3)/C - Ball in Berland/C_김민수.java

|name|A|B|C|D|E|F|G|
|김민수|O|O|△|-|-|-|-|
3번 long의 저주에서 못헤어 나왔습니다...

2021/11/13 Codeforces Round #697 (Div. 3) --- 김민수

---

weekly_codeforces/M11/D20 - Codeforces Round #693 (Div. 3)/A - Cards for Friends/A_우지현.cpp
weekly_codeforces/M11/D20 - Codeforces Round #693 (Div. 3)/B - Fair Division/B_우지현.cpp
weekly_codeforces/M11/D20 - Codeforces Round #693 (Div. 3)/C - Long Jumps/C_우지현.cpp

|name|A|B|C|D|E|F|G|
|------|-|-|-|-|-|-|-|
|우지현|O|O|O|X||||

2021/11/20 Codeforces Round #693 (Div. 3) --- 우지현

---

weekly_codeforces/M11/D20 - Codeforces Round #693 (Div. 3)/A - Cards for Friends/A_김서진.java
weekly_codeforces/M11/D20 - Codeforces Round #693 (Div. 3)/B - Fair Division/B_김서진.java
weekly_codeforces/M11/D20 - Codeforces Round #693 (Div. 3)/C - Long Jumps/C_김서진.java

|name|A|B|C|D|E|F|G|
|------|-|-|-|-|-|-|-|
|{{your name}}|O|O|O|X||||

2021/11/20 Codeforces Round #693 (Div.3) --- 김서진

---

weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/A - Special Permutation/A_한승주.py
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/B - Unique Bid Auction/B_한승주.py
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/C - Sequence Transformation/C_한승주.py
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/D - Number into Sequence/D_한승주.py
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/E - Number of Simple Paths/E_한승주.py

|name|A|B|C|D|E1|E2|F|
|------|-|-|-|-|-|-|-|
|{{your name}}|O|O|O|O|O|X|X|
E2 아직 해결 못해씀니당..
오늘 풀고 마무리해보겠슴니다

2021/12/04 Codeforces Round #690 (Div. 3) --- 한승주

---

weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/A - Special Permutation/A_한승주.py
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/B - Unique Bid Auction/B_한승주.py
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/C - Sequence Transformation/C_한승주.py
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/D - Number into Sequence/D_한승주.py
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/E - Number of Simple Paths/E_한승주.py

|name|A|B|C|D|E|F|
|------|-|-|-|-|-|-|
|한승주|O|O|O|O|△||
E는 cycle에서부터 뻗어나가는 tree들에 대한 경우의 수를 제거.
F는 세그멘트 트리라 안품.

2021/12/11 Codeforces Round #686 (Div. 3) --- 한승주

---

weekly_codeforces/M12/D04 - Codeforces Round #690 (Div. 3)/A - Favorite Sequence/A_김민수.java
weekly_codeforces/M12/D04 - Codeforces Round #690 (Div. 3)/B - Last Year's Substring/B_김민수.java
weekly_codeforces/M12/D04 - Codeforces Round #690 (Div. 3)/C - Unique Number/C_김민수.java

|name|A|B|C|D|E|F|G|
|김민수|O|O|▵|-|-|-|-|

2021/12/04 Codeforces Round #690 (Div. 3) --- 김민수

---

weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/A - Special Permutation/A_우지현.cpp
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/B - Unique Bid Auction/B_우지현.cpp
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/C - Sequence Transformation/C_우지현.cpp
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/D - Number into Sequence/D_우지현.cpp

|name|A|B|C|D|E|F|
|------|-|-|-|-|-|-|
|우지현|O|O|O|O|||

2021/12/11 Codeforces Round #686 (Div. 3) --- 우지현

---

weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/A - Special Permutation/A_김민수.java
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/B - Unique Bid Auction/B_김민수.java
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/C - Sequence Transformation/C_김민수.java
weekly_codeforces/M12/D11 - Codeforces Round #686 (Div. 3)/D - Number into Sequence/D_김민수.java

2021/12/11 Codeforces Round #686 (Div. 3) --- 김민수
